export APPROOT="http://localhost:3000"
export HOST="127.0.0.1"
export PORT="3000"
export IP_FROM_HEADER="true"
export PGHOST="localhost"
export PGPORT="5432"
export PGUSER="glot"
export PGPASS="glot"
export PGDATABASE="glot"
export RUN_API_BASE_URL="http://localhost:8089"
export RUN_API_ADMIN_TOKEN="admin-token"
export RUN_API_ANONYMOUS_TOKEN="anon-token"
export SNIPPETS_API_BASE_URL="http://localhost:8090"
export SNIPPETS_API_ADMIN_TOKEN="admin-token"
export MAILGUN_DOMAIN="example.com"
export MAILGUN_API_KEY="key-12345"
export EMAIL_FROM_ADDRESS="glot@glot.io"
#export ANALYTICS_ID=""

stack exec yesod devel
